server:
  port: 8081

spring:
  application:
    name: whatsapp-dispatcher

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: whatsapp-group
      auto-offset-reset: earliest
      # Aqui entram os tradutores (Key e Value Deserializer)
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: "*" # O "Visto de Confian√ßa"